In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
dataset=pd.read_csv('/kaggle/input/stroke-prediction-dataset/healthcare-dataset-stroke-data.csv')

In [12]:
df=pd.DataFrame(dataset)

In [21]:
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [23]:
df.drop(['id','ever_married'],axis=1,inplace=True)

In [24]:
df.head()

gender   age  hypertension  heart_disease      work_type Residence_type  \
0    Male  67.0             0              1        Private          Urban   
1  Female  61.0             0              0  Self-employed          Rural   
2    Male  80.0             0              1        Private          Rural   
3  Female  49.0             0              0        Private          Urban   
4  Female  79.0             1              0  Self-employed          Rural   

   avg_glucose_level   bmi   smoking_status  stroke  
0             228.69  36.6  formerly smoked       1  
1             202.21   NaN     never smoked       1  
2             105.92  32.5     never smoked       1  
3             171.23  34.4           smokes       1  
4             174.12  24.0     never smoked       1

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   work_type          5110 non-null   object 
 5   Residence_type     5110 non-null   object 
 6   avg_glucose_level  5110 non-null   float64
 7   bmi                4909 non-null   float64
 8   smoking_status     5110 non-null   object 
 9   stroke             5110 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 399.3+ KB


In [28]:
print(np.unique(df['gender']),np.unique(df['work_type']),np.unique(df['Residence_type']),np.unique(df['smoking_status']))

['Female' 'Male' 'Other'] ['Govt_job' 'Never_worked' 'Private' 'Self-employed' 'children'] ['Rural' 'Urban'] ['Unknown' 'formerly smoked' 'never smoked' 'smokes']


In [39]:
df=pd.get_dummies(df,columns=['gender','work_type','Residence_type','smoking_status'],drop_first=True)

In [41]:
df.head()

age  hypertension  heart_disease  avg_glucose_level   bmi  stroke  \
0  67.0             0              1             228.69  36.6       1   
1  61.0             0              0             202.21   NaN       1   
2  80.0             0              1             105.92  32.5       1   
3  49.0             0              0             171.23  34.4       1   
4  79.0             1              0             174.12  24.0       1   

   gender_Male  gender_Other  work_type_Never_worked  work_type_Private  \
0            1             0                       0                  1   
1            0             0                       0                  0   
2            1             0                       0                  1   
3            0             0                       0                  1   
4            0             0                       0                  0   

   work_type_Self-employed  work_type_children  Residence_type_Urban  \
0                        0                   0                     1   
1                        1                   0                     0   
2                        0                   0                     0   
3                        0                   0                     1   
4                        1                   0                     0   

   smoking_status_formerly smoked  smoking_status_never smoked  \
0                               1                            0   
1                               0                            1   
2                               0                            1   
3                               0                            0   
4                               0                            1   

   smoking_status_smokes  
0                      0  
1                      0  
2                      0  
3                      1  
4                      0

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   age                             5110 non-null   float64
 1   hypertension                    5110 non-null   int64  
 2   heart_disease                   5110 non-null   int64  
 3   avg_glucose_level               5110 non-null   float64
 4   bmi                             4909 non-null   float64
 5   stroke                          5110 non-null   int64  
 6   gender_Male                     5110 non-null   uint8  
 7   gender_Other                    5110 non-null   uint8  
 8   work_type_Never_worked          5110 non-null   uint8  
 9   work_type_Private               5110 non-null   uint8  
 10  work_type_Self-employed         5110 non-null   uint8  
 11  work_type_children              5110 non-null   uint8  
 12  Residence_type_Urban            51

In [46]:
df.isnull().sum()

age                                 0
hypertension                        0
heart_disease                       0
avg_glucose_level                   0
bmi                               201
stroke                              0
gender_Male                         0
gender_Other                        0
work_type_Never_worked              0
work_type_Private                   0
work_type_Self-employed             0
work_type_children                  0
Residence_type_Urban                0
smoking_status_formerly smoked      0
smoking_status_never smoked         0
smoking_status_smokes               0
dtype: int64

In [50]:
df['bmi'].median()

28.1

In [51]:
df['bmi']=df['bmi'].fillna(df['bmi'].median())

In [52]:
df.isnull().sum()

age                               0
hypertension                      0
heart_disease                     0
avg_glucose_level                 0
bmi                               0
stroke                            0
gender_Male                       0
gender_Other                      0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
Residence_type_Urban              0
smoking_status_formerly smoked    0
smoking_status_never smoked       0
smoking_status_smokes             0
dtype: int64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   age                             5110 non-null   float64
 1   hypertension                    5110 non-null   int64  
 2   heart_disease                   5110 non-null   int64  
 3   avg_glucose_level               5110 non-null   float64
 4   bmi                             5110 non-null   float64
 5   stroke                          5110 non-null   int64  
 6   gender_Male                     5110 non-null   uint8  
 7   gender_Other                    5110 non-null   uint8  
 8   work_type_Never_worked          5110 non-null   uint8  
 9   work_type_Private               5110 non-null   uint8  
 10  work_type_Self-employed         5110 non-null   uint8  
 11  work_type_children              5110 non-null   uint8  
 12  Residence_type_Urban            51

In [57]:
df['heart_disease'].value_counts()

0    4834
1     276
Name: heart_disease, dtype: int64

In [58]:
df['stroke'].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

In [61]:
X=df.drop('stroke',axis=1)

In [62]:
y=df['stroke']

In [63]:
print(X.shape,y.shape)

(5110, 15) (5110,)


In [60]:
from sklearn.model_selection import train_test_split

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=22)

In [69]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(3577, 15) (3577,) (1533, 15) (1533,)


In [70]:
from sklearn.tree import DecisionTreeClassifier

In [71]:
dtc=DecisionTreeClassifier()

In [72]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [73]:
preds=dtc.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix,classification_report

In [75]:
confusion_matrix(preds,y_test)

array([[1373,   76],
       [  72,   12]])

In [77]:
print("accuracy: ",(1373/(1373+12+76+72))*100)

accuracy:  89.56294846705805


In [79]:
print(classification_report(preds,y_test))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1449
           1       0.14      0.14      0.14        84

    accuracy                           0.90      1533
   macro avg       0.54      0.55      0.54      1533
weighted avg       0.91      0.90      0.90      1533



In [80]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
rf=RandomForestClassifier(n_estimators=200,min_samples_leaf=10)

In [88]:
rf.fit(X_train,y_train)

RandomForestClassifier(min_samples_leaf=10, n_estimators=200)

In [89]:
preds_rf=rf.predict(X_test)

In [90]:
confusion_matrix(preds_rf,y_test)

array([[1445,   88],
       [   0,    0]])

In [91]:
print("Accuracy: ",(1445/(1445+88))*100)

Accuracy:  94.25962165688193


In [92]:
print(classification_report(preds,y_test))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1449
           1       0.14      0.14      0.14        84

    accuracy                           0.90      1533
   macro avg       0.54      0.55      0.54      1533
weighted avg       0.91      0.90      0.90      1533



In [93]:
from sklearn.ensemble import AdaBoostClassifier

In [94]:
abc=AdaBoostClassifier()

In [95]:
abc.fit(X_train,y_train)

AdaBoostClassifier()

In [96]:
preds_abc=abc.predict(X_test)

In [97]:
confusion_matrix(preds_abc,y_test)

array([[1440,   84],
       [   5,    4]])

In [98]:
print(classification_report(preds_abc,y_test))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97      1524
           1       0.05      0.44      0.08         9

    accuracy                           0.94      1533
   macro avg       0.52      0.69      0.53      1533
weighted avg       0.99      0.94      0.96      1533

